### PR TITLE
ENH: Convert build-system and sources into a VTK 9.x module

### PR DESCRIPTION
**Pull request by jcfr**
* Add vtk.module and update CMakeLists.txt to use VTK module API

* Move vtkU3DExporterTest.cxx into Testing/Cxx to match VTK module convention

* Update vtkU3DExporter to support building against VTK >= 8.90

* Update vtkU3DExporterTest to adapt to updated VTK pipelining API

### CODE REVIEW

**Comment by jcfr** [comment]
### Building the module

```
ROOT_DIR=/home/jcfr/Projects
CMAKE=/home/jcfr/Support/cmake-3.22.2-linux-x86_64/bin/cmake
```

```
VTK_EXTERNAL_MODULE_SOURCE_DIR=${ROOT_DIR}VTKExternalModule
git clone KitwareMedical/VTKExternalModule ${VTK_EXTERNAL_MODULE_SOURCE_DIR}

cd ~/Projects
mkdir VTKU3DExporter-cp38-cp38-linux_x86_64
cd $_

MODULE_SOURCE_DIR=${ROOT_DIR}/VTKU3DExporter
MODULE_BINARY_DIR=${ROOT_DIR}/VTKU3DExporter-cp38-cp38-linux_x86_64
VTK_SOURCE_DIR=${ROOT_DIR}/vtk
VTK_DIR=${ROOT_DIR}/vtk-cp38-cp38-linux_x86_64

U3D_INCLUDE_DIR=${ROOT_DIR}/U3D-install/u3d/include/
U3D_IDTF_LIBRARY=${ROOT_DIR}/U3D-install/u3d/libIDTF.so
```

```
${CMAKE} \
  -DVTK_MODULE_NAME:STRING=U3DExporter \
  -DVTK_MODULE_SOURCE_DIR:PATH=${MODULE_SOURCE_DIR} \
  -DVTK_MODULE_CMAKE_MODULE_PATH:PATH=${VTK_SOURCE_DIR}/CMake \
  -DVTK_DIR:PATH=${VTK_DIR} \
  -DU3D_INCLUDE_DIR:PATH=${U3D_INCLUDE_DIR} \
  -DU3D_IDTF_LIBRARY:FILEPATH=${U3D_IDTF_LIBRARY} \
  -S ${VTK_EXTERNAL_MODULE_SOURCE_DIR} -B ${MODULE_BINARY_DIR}
  

${CMAKE} \
  --build ${MODULE_BINARY_DIR} -- -j8
```

**Comment by jcfr** [comment]
Ater attempting to run the `VTK::U3DExporterCxx-vtkU3DExporterTest` test, it currently fails with the following

```
ctest -V 

1: <DartMeasurement name="ImageNotFound" type="text/string">/home/jcfr/Projects/VTKU3DExporter-cp38-cp38-linux_x86_64/Data/Use_-V_for_Baseline</DartMeasurement>
1: <DartMeasurementFile name="TestImage" type="image/png">/home/jcfr/Projects/VTKU3DExporter-cp38-cp38-linux_x86_64/Testing/Temporary/Use_-V_for_Baseline</DartMeasurementFile><DartMeasurement name="WallTime" type="numeric/double">0.0725451</DartMeasurement>
1: <DartMeasurement name="CPUTime" type="numeric/double">0.065532</DartMeasurement>
1/1 Test #1: VTK::U3DExporterCxx-vtkU3DExporterTest ...***Failed  Error regular expression found in output. Regex=[DartMeasurement name=.ImageNotFound]  0.24 sec
```

That said, the test generates `test.png`, `test.wrl` and `test.x3d`

test

**Comment by jcfr** [comment]
## Attempt to run `test.py`

```diff
diff --git a/test.py b/test.py
index d06846b..3a69498 100644
--- a/test.py
+++ b/test.py
@@ -3,7 +3,7 @@ import tempfile
 import vtk
 from vtk.util.keys import StringKey
 from vtk.vtkCommonCore import vtkInformationIterator
-import vtku3dexporter
+import vtkU3DExporter
 
 
 def write_u3d(file_path, actors):
@@ -17,7 +17,7 @@ def write_u3d(file_path, actors):
 
     renderer.ResetCamera()
 
-    u3d_exporter = vtku3dexporter.vtkU3DExporter()
+    u3d_exporter = vtkU3DExporter.vtkU3DExporter()
     u3d_exporter.SetFileName(file_path)
     u3d_exporter.SetInput(render_window)
     u3d_exporter.Write()
```

```
LD_LIBRARY_PATH=${MODULE_BINARY_DIR}/lib/ PYTHONPATH=${MODULE_BINARY_DIR}/lib/python3.8/site-packages/vtkmodules/ python ../VTKU3DExporter/test.py 
Writing file to /tmp/test_report.u3d
Testing that u3d was generated...
Traceback (most recent call last):
  File "../VTKU3DExporter/test.py", line 103, in <module>
    raise Exception("Failed to create the U3D file")
Exception: Failed to create the U3D file

```

**Comment by Korijn** [comment]
Nice work!

* It's definitely critical that `test.py` passes.
* What would it take to run this test on CI and/or Docker?

**Comment by Korijn** [comment]
If you are OK with it, I would like to merge the branch and this point, and continue on a new Pull Request.

I will then add a test for PyInstaller support.

**Comment by jcfr** [comment]
> would like to merge the branch and this point

The branch has been merged :rocket: 

> then add a test for PyInstaller support (I want to be sure the U3D_LIB workaround will work in that deployment scenario)

Once https://github.com/ClinicalGraphics/VTKU3DExporter/pull/2 is merged, creating new pull-request against `main` will trigger the build & test.

**Pull request merged**
